(function(g){var window=this;var Pya=function(a,b,c,d){c=(0,g.B)(c,d||a.A);b=g.aG(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},Qya=function(a){a.o||(a.o=new g.DD,g.M(a,a.o));
return a.o},a2=function(a){a.U("cardstatechange",g.zU(a)&&g.AU(a)?1:0)},Uya=function(a){var b=g.Gh(a,"fontSize");
var c=(c=b.match(Rya))&&c[0]||null;if(b&&"px"==c)return(0,window.parseInt)(b,10);if(g.Qd){if(String(c)in Sya)return g.Zh(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Tya)return a=a.parentNode,c=g.Gh(a,"fontSize"),g.Zh(a,b==c?"1em":b,"left","pixelLeft")}c=g.Vd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.ce(c);return b},b2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},Vya=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Jk&&a.dataset){if(g.tc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Kb("pollChoiceIndex"))},e2=function(a){a=g.Ga(a);
delete c2[a];g.ec(c2)&&d2&&d2.stop()},Xya=function(){d2||(d2=new g.V(function(){Wya()},20));
var a=d2;a.isActive()||a.start()},Wya=function(){var a=(0,g.I)();
g.Ob(c2,function(b){Yya(b,a)});
g.ec(c2)||Xya()},Zya=function(a,b){g.vf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},f2=function(a,b,c,d){g.du.call(this);
if(!g.Ba(a)||!g.Ba(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.C=null},Yya=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.C);a.C=b;$ya(a,a.progress);1==a.progress?(a.o=0,e2(a),a.Ld(),a.pn()):a.tb()&&a.Wv()},$ya=function(a,b){g.Da(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},g2=function(a,b,c,d,e){f2.call(this,b,c,d,e);
this.element=a},h2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
g2.apply(this,arguments)},aza=function(a){return Math.pow(a,3)},bza=function(a){return 3*a*a-2*a*a*a},i2=function(a,b){(0,g.D)(b,function(b){g.YG("visualElementShown",{csn:a,
ve:g.gH(b),eventType:4},g.cH)})},j2=function(a,b){(0,g.D)(b,function(b){g.YG("visualElementHidden",{csn:a,
ve:g.gH(b),eventType:8},g.cH)})},k2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Od=b.session_data||{};this.B=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={CM:a.impression,click:a.click,close:a.close,UW:a.teaser_impression,Ww:a.teaser_click};b=b.tracking_params||{};this.F=g.fH(b.card);this.H=g.fH(b.teaser);this.D=g.fH(b.icon)},l2=function(a,b){g.Wf.call(this);
this.im=a;this.Ht=b;this[g.Af]=!1},p2=function(a,b,c,d){l2.call(this,a,b);
a=this.Ht;b=this.ma();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.Xa(),g.w(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",(0,window.parseFloat)(c)/cza(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Ht;a=this.ma();if(d instanceof m2)a.setAttribute("fill",d.J),a.setAttribute("fill-opacity",d.K);else if(d instanceof n2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=o2(c,"linearGradient",
{x1:d.D,y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.xa(d.B)&&(f+=";stop-opacity:"+d.B);f=o2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.xa(d.C)&&(f+=";stop-opacity:"+d.C);d=o2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=dza(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},eza=function(){},fza=function(a,b){l2.call(this,a,b)},q2=function(){this.vb=[];
this.Na=[];this.Re=[]},r2=function(a,b,c,d){var e=a.ke[0]-b*Math.cos(g.zd(d))+b*Math.cos(g.zd(d+90)),f=a.ke[1]-c*Math.sin(g.zd(d))+c*Math.sin(g.zd(d+90));
a.vb.push(3);a.Na.push(1);a.Re.push(b,c,d,90,e,f);a.Gn=!1;a.ke=[e,f]},hza=function(a,b){for(var c=a.Re,d=0,e=0,f=a.vb.length;e<f;e++){var k=a.vb[e],l=gza[k]*a.Na[e];
b(k,c.slice(d,d+l));d+=l}},iza=function(a,b,c,d){p2.call(this,a,b,c,d)},s2=function(a,b){this.A=a;
this.o=b},t2=function(a,b,c,d,e){g.Bv.call(this,e);
this.width=a;this.height=b;this.C=c||null;this.M=d||null},cza=function(a){var b=a.Tj();
return b?b.width/(a.C?new g.Cd(a.C,a.M):a.Tj()).width:0},jza=function(a,b){l2.call(this,a,b)},n2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.B=g.u(k)?k:null;this.C=g.u(l)?l:null},m2=function(a,b){this.J=a;
this.K=null==b?1:b},u2=function(a,b){l2.call(this,a,b)},kza=function(a,b,c,d){p2.call(this,a,b,c,d)},v2=function(a,b){l2.call(this,a,b)},w2=function(a,b,c,d,e){t2.call(this,a,b,c,d,e);
this.A={};this.O=g.Sd&&!g.Ac(526);this.K=new g.qn(this)},o2=function(a,b,c){a=a.J.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&x2(a,c);return a},x2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},y2=function(a,b,c,d){b=o2(a,"path",{d:lza(b)});
c=new kza(b,a,c,d);a.B.ma().appendChild(c.ma())},lza=function(a){var b=[];
hza(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},dza=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+mza++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},nza=function(){z2||(z2=new g.Hg(400),z2.start());
return z2},A2=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.J)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=(0,window.parseInt)(a.startMs,10);f.impressionUrls=(0,g.J)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.fH(a.trackingParams);var k=(0,g.J)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,v=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.cA=k.image;l.left=(0,window.parseFloat)(k.left);l.width=(0,window.parseFloat)(k.width);l.top=(0,window.parseFloat)(k.top);
l.aspectRatio=(0,window.parseFloat)(k.aspectRatio);l.startMs=(0,window.parseInt)(k.startMs,10);l.endMs=(0,window.parseInt)(k.endMs,10);l.clickUrls=(0,g.J)(v.loggingUrls||[],c);l.ro=g.$b(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.J)(k.impressionUrls||[],c);l.PL=(0,g.J)(k.hovercardShowUrls||[],c);l.Od={itct:k.trackingParams};l.visualElement=g.fH(k.trackingParams);if("VIDEO"==m)l.targetUrl=v.urlEndpoint?v.urlEndpoint.url:e(v.watchEndpoint),l.Ip=!1,l.kr=b,l.videoDuration=
d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=v.urlEndpoint?v.urlEndpoint.url:e(v.watchEndpoint),l.Ip=!1,l.kr=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.$b(v,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Ip=!1;l.kr="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){v=d(m.unsubscribedButtonText);var z=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);
var G=d(m.subscriberCountText)}else E=d(m.subscriberCountText),G=d(m.subscriberCountWithSubscribeText);var L=null;if(k.signinEndpoint&&(L=g.$b(k,"signinEndpoint","webNavigationEndpointData","url"),!L)){k=void 0;break a}if(v&&(z||L)){k={subscribed:m.subscribed,subscribeText:v,subscribeCount:E,unsubscribeText:z,unsubscribeCount:G,enabled:m.enabled,signinUrl:L,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=
g.$b(v,"urlEndpoint","url"),l.Ip=!0,l.kr="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.de)(k,function(a){return!!a});
return f},B2=function(a){g.UU.call(this,a);
this.A=null;this.K=!1;this.C=null;this.o={};this.G={};this.F=this.B=null;this.L=[];a=g.Z(a);this.M=g.rN(a)||g.sN(a);this.cG=!0;this.H=0;this.J=new g.Ep(null);this.D=new g.fG(this);g.M(this,this.D);this.D.R(this.player,g.KQ("creatorendscreen"),this.DN);this.D.R(this.player,"crx_creatorendscreen",this.EN);this.D.R(this.player,"resize",this.mC);this.D.R(window,"focus",this.KV);this.load();var b=g.Xd("STYLE");(window.document.getElementsByTagName("HEAD")[0]||window.document.body).appendChild(b);g.sf(this,
function(){g.ce(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},oza=function(a){return a.player.getVideoData().isDni?"current":a.M?"new":"current"},C2=function(a){return"creator-endscreen-editor"===a},D2=function(a,b){g.IU(a.player,"creatorendscreen");
a.B&&(a.B.dispose(),a.B=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(a){a.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){pza(a);c=[];var d=new g.IQ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Z(a.player).A||(a.B=new g.W({I:"div",N:"ytp-ce-shadow"}),g.KU(a.player,a.B.element,4),a.F=new g.rV(a.B,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=qza(a,e);a.o[e.id]=f;a.G[e.id]=e;g.KU(a.player,f.element,4);var k=new g.IQ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);rza(a,f,e)}g.EU(a.player,
c);a.mC()}},pza=function(a){var b=g.yH(),c=g.zH();
c&&b&&g.iH(c,b,[a.A.visualElement])},qza=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",ea:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.ro||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:E2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ea:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.Fp(a.J,b.title||"")},da:b.title},{I:"div",N:"ytp-ce-video-duration",da:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={I:"div",ea:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.ro||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:E2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ea:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.Fp(a.J,b.title||"")},da:b.title},{I:"div",N:"ytp-ce-playlist-count",P:[{I:"div",
N:"ytp-ce-playlist-icon"},{I:"div",N:"ytp-ce-playlist-count-text",da:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={I:"div",ea:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.ro||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body",P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"a",ea:["ytp-ce-channel-title","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Fp(a.J,b.title||"")},da:b.title},b.subscribeButton?{I:"div",N:"ytp-ce-subscribe-container",P:[{I:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",N:"ytp-ce-channel-subscribers-text",da:b.subscribersText}:"",b.metadata?{I:"div",ea:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],da:b.metadata}:""]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:E2(b)}]};c=new g.W(c);var d=g.Id(window.document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.T(d,"ytp-ce-subscribe-button");if(g.Z(a.player).A){var e=null;var f=b.Od.itct}else e="endscreen",f=null;e=new g.d_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={I:"div",ea:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.ro||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",P:[{I:"div",N:"ytp-ce-expanding-overlay-body",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"div",N:"ytp-ce-website-title",T:{dir:g.Fp(a.J,b.title||"")},da:b.title},{I:"div",N:"ytp-ce-website-metadata",da:b.metadata},{I:"a",ea:["ytp-ce-website-goto","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1"},da:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:E2(b)},{I:"div",N:"ytp-ce-expanding-icon",T:sza(b.iconUrl)}]},c=new g.W(c)}b.o&&g.T(c.element,"ytp-ce-placeholder");return c},E2=function(a){if(a.cA)var b=
a.cA.thumbnails;
return sza(b?b[b.length-1].url:null)},sza=function(a){return a?{style:"background-image: url("+a+")"}:{}},rza=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.W("mouseenter",(0,g.B)(a.Tu,a,b,c));b.W("mouseleave",(0,g.B)(a.ew,a,b,c));g.Z(a.player).A||b.W("click",(0,g.B)(function(a){g.T(a.element,"ytp-ce-element-hover")},a,b));
b.W("click",(0,g.B)(a.XD,a,c));b.W("keypress",(0,g.B)(a.XD,a,c));b.W("focus",(0,g.B)(function(a,b){this.Tu(a,b)},a,b,c));
b.W("blur",(0,g.B)(function(a,b){this.ew(a,b)},a,b,c));
b.W("touchstart",(0,g.B)(a.Tu,a,b,c));var f=g.Kd("ytp-ce-expanding-overlay-hider",b.element);f&&b.R(f,"touchstart",function(a){a=a||window.event;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();g.Uq(b.element,"ytp-ce-element-hover");g.Uq(b.element,"ytp-ce-force-expand")});
b.W("keydown",(0,g.B)(function(a,b){this.cG=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.B)(function(a,b,c){this.H+=c;0<this.H?(g.T(a.element,"ytp-ce-force-expand"),F2(this,b.id,!0)):(g.Uq(a.element,"ytp-ce-force-expand"),g.Uq(a.element,"ytp-ce-element-hover"),F2(this,b.id,!1))},a,b,c);
a=(0,g.B)(function(a,b){b&&(a.W("blur",function(){g.Yh(b)&&this.cG&&b.focus()}),a.R(b,"focus",d),a.R(b,"blur",e))},a,b);
a(g.Kd("ytp-sb-subscribe",b.element));a(g.Kd("ytp-sb-unsubscribe",b.element));b.W("focus",d);b.W("blur",e)},F2=function(a,b,c){a.B&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.U(a.o[d].element,"ytp-ce-element-shadow-show",c)},G2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||C2(g.Z(a.player).playerStyle))c&&c();else{b=tza(a,b);var e=0,f=!1,k=new g.V(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.iF(b[a],d)}},H2=function(a,b,c){G2(a,b.clickUrls,c);
(a=g.zH())&&b.Ip&&g.kH(a,b.visualElement)},tza=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(uza(b[e],c));return d},uza=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=(0,window.unescape)(a);
c=c.substring(1,c.length-1);return b[c]?(0,window.escape)(b[c]):a})},I2=function(a){return g.Ba(a)&&a.length?a[0]:a},J2=function(a){var b=/.+/;
return g.w(a)&&null!=b&&null!=a&&a.match(b)?a:""},K2=function(a,b){if(null==a)return b;
var c=(0,window.parseInt)(a,0);if((0,window.isNaN)(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},L2=function(a){return g.w(a)?a:""},M2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},N2=function(a,b){return"true"==a||"false"==a?"true"==a:b},O2=function(a,b){return g.w(a)?(0,window.parseFloat)(a):b},P2=function(a,b,c,d,e){a=(0,window.parseFloat)(a);
if(null!=a&&!(0,window.isNaN)(a)){if(d)return g.wd(a,b,c);if(a>=b&&a<=c)return a}return e},vza=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.D)(a,function(a){a=(0,window.parseFloat)(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},Q2=function(a,b){if(null==a)return null;
if(g.Ca(a)){var c=[];(0,g.D)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},wza=function(a){function b(a){return null!=a&&!(0,window.isNaN)(a)}
return(a=a?new g.mh((0,window.parseFloat)(a.top),(0,window.parseFloat)(a.right),(0,window.parseFloat)(a.bottom),(0,window.parseFloat)(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},xza=function(a){function b(a){return(0,g.de)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},yza=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},R2=function(a){if(!a)return null;
var b=g.Xc(L2(a.value));b=g.Uc(b);if(!b)return null;var c=M2(a.target,zza,"current");return null==c?null:new yza(b,c,N2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},S2=function(a){return a.value?a.value:null},Aza=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Dza=function(a){if(!a)return null;
var b=M2(a.type,Bza),c=M2(a.trigger,Cza),d=I2(a.url);d=R2(d?d:null);I2(a.subscribeData);return b?new Aza(b,c,d):null},Eza=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},T2=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},U2=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.ol=c;this.B=d;this.t=e;this.D=f;this.F=k;this.G=l;this.C=m;this.A=n;this.o=p},Gza=function(a,b){if(!a)return null;
var c=O2(a.x,0),d=O2(a.y,0),e=O2(a.w,0),f=O2(a.h,0),k=vza(a.t),l=O2(a.d,0),m=O2(a.px,0),n=O2(a.py,0),p=O2(a.scaleSlope,1),t=O2(a.scaleSlopeX,p);p=O2(a.scaleSlopeY,p);var v=M2(a.scaleDimension,Fza,"xy");return b(c,d,e,f,k,l,m,n,t,p,v)},V2=function(a,b){var c=Hza(b,Iza(a,new g.ph(a.x,a.y,a.ol,a.B),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.wd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.wd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},Iza=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=Eza(c,a.C,f);
a=T2(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.ph(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},Jza=function(a){return a?Gza(a,function(a,c,d,e,f,k,l,m,n,p,t){return new U2(a,c,d,e,f,k,l,m,n,p,t)}):null},Kza=function(a,b){this.o=a;
this.A=b||null},Hza=function(a,b){var c=a.A?V2(a.A,new Kza(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Ad?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.xa(c)&&(d.top+=c));return d},Lza=function(a,b,c,d,e,f,k,l,m,n,p,t,v){U2.call(this,a,b,c,d,e,l,m,n,p,t,v);
this.H=f;this.J=k},Mza=function(a){if(!a)return null;
var b=O2(a.sx,0),c=O2(a.sy,0);return Gza(a,function(a,e,f,k,l,m,n,p,t,v,z){return new Lza(a,e,f,k,l,b,c,m,n,p,t,v,z)})},Nza=function(a,b,c,d,e,f,k,l,m,n,p,t,v,z){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.B=k;this.textAlign=l;this.textSize=m;this.C=n;this.padding=p;this.effects=t;this.cornerRadius=v;this.D=z},Pza=function(a){if(!a)return null;
var b=K2(a.fgColor,"#1A1A1A"),c=K2(a.bgColor,"#FFF"),d=K2(a.borderColor,"#000"),e=P2(a.borderWidth,0,5,!1,0),f=P2(a.bgAlpha,0,1,!1,.8),k=K2(a.highlightFontColor,"#F2F2F2"),l=P2(a.highlightWidth,0,5,!1,3),m=L2(a.textAlign),n=P2(a.textSize,3.3,30.1,!0,3.6107),p=L2(a.fontWeight),t=wza(a.padding),v=xza(a.effects),z=P2(a.cornerRadius,0,10,!0,0);a=I2(a.gradient);if(a=a?a:null){var E=P2(a.x1,0,100,!0,0),G=P2(a.y1,0,100,!0,0),L=P2(a.x2,0,100,!0,100),O=P2(a.y2,0,100,!0,100),Ka=K2(a.color1,"#FFF"),jb=K2(a.color2,
"#000");a=new Oza(E,G,L,O,Ka,jb,P2(a.opacity1,0,100,!0,100),P2(a.opacity2,0,100,!0,0))}else a=null;return new Nza(b,c,d,e,f,k,l,m,n,p,t,v,z,a)},Oza=function(a,b,c,d,e,f,k,l){this.B=a;
this.D=b;this.C=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},Qza=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.B=d},Sza=function(a){if(!a)return null;
var b=M2(a.type,Rza,"rect"),c=Q2(a.rectRegion,Jza),d=Q2(a.anchoredRegion,Mza);a=Q2(a.shapelessRegion,Jza);return new Qza(b,c,d,a)},Tza=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.B&&a.B.length?a.B[0]:null},Uza=function(a,b){this.A=a;
this.o=b},Vza=function(a,b){this.state=a;
this.ref=b},Xza=function(a){if(!a)return null;
var b=M2(a.state,Wza);a=J2(a.ref);return b?new Vza(b,a):null},Yza=function(a,b,c,d){this.o=a||[];
this.B=b||[];this.C=c;this.A=d;this.value=!1},Zza=function(a){if(!a)return null;
var b=Q2(a.condition,Xza),c=Q2(a.notCondition,Xza),d=N2(a.show_delay,!1);a=N2(a.hide_delay,!1);return b||c?new Yza(b,c,d,a):null},$za=function(a,b,c){(0,g.D)(a.o,g.Ha(b,!1),c);
(0,g.D)(a.B,g.Ha(b,!0),c)},W2=function(a,b,c,d,e,f,k,l,m,n,p,t,v,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.C=e;this.segment=f;this.B=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=t;this.o=v;this.itct=z},cAa=function(a){if(!a)return null;
var b=J2(a.id),c=J2(a.author),d=M2(a.type,aAa),e=M2(a.style,X2),f=L2(I2(a.TEXT)),k=L2(a.data);k=0!=k.length?JSON.parse(k):{};var l=I2(a.segment);var m=l?l:null;m?(J2(m.timeRelative),l=J2(m.spaceRelative),l=(m=Q2(m.movingRegion,Sza))?new Uza(l,m):null):l=null;m=Q2(a.action,Dza);var n=Q2(a.trigger,Zza),p=I2(a.appearance);(p=Pza(p?p:null))||(p=Pza({}));var t=M2(a.coordinate_system,bAa,"video_relative"),v=N2(a.closeable,!0),z=L2(a.log_data);a=L2(a.itct);return b&&d?new W2(b,c,d,e,f,l,m,n,p,t,v,k,z,a):
null},Z2=function(a){return Y2(a,function(a){return"click"==a.trigger})},Y2=function(a,b){return(0,g.Tj)(a.B,b,void 0)},dAa=function(a,b,c){(0,g.D)(a.B,b,c)},eAa=function(a,b){return g.Oa(a.B,b,void 0)},fAa=function(a,b,c){(0,g.D)(a.G,b,c)},gAa=function(a,b){(0,g.J)(a.G,b,void 0)},$2=function(a){return(a=hAa(a))?Tza(a):null},hAa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},iAa=function(a,b){var c=$2(a);
return c&&b?T2(b,c.A,c.o?c.o:"xy"):1},kAa=function(a,b,c){this.o={};
this.B=!1;this.D="ivTrigger:"+a;this.A=c;$za(b,function(a,b){var c=jAa(b.state,b.ref);this.A.subscribe(c,(0,g.B)(this.C,this,c,a));this.o[c]=a},this)},jAa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},a3=function(){this.o=!1;
this.D=this.A=null},b3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new w2(b,c,void 0,void 0,void 0),a.A=b,a.A.tp(),a.D=g.Vd("DIV"),b=a.A.ma(),a.D.appendChild(b));
return a.A},c3=function(a,b,c){var d=window.document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Ob(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},d3=function(a,b){var c=":"+(g.Av.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},lAa=function(a,b){var c=d3(a,c3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=d3(a,c3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},c3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=d3(a,c3("feComposite",{"in":c,in2:b,operator:"in"}));return d3(a,c3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},mAa=function(a,b){var c=d3(a,c3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=d3(a,c3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=d3(a,c3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=d3(a,c3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=d3(a,c3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=d3(a,c3("feComposite",{operator:"out","in":c,in2:d}));return d3(a,c3("feComposite",{operator:"over","in":b,in2:c}))},nAa=function(a,b){return b},oAa=function(a){var b=
c3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.D)(a,function(a){a:{switch(a){case "bevel":a=lAa;break a;case "dropshadow":a=mAa;break a}a=nAa}c=a(b,c)});
return b},pAa=function(a){a=(0,g.de)(a,function(a){return a in e3});
g.nb(a,function(a,c){return e3[a]-e3[c]});
return a},qAa=function(a){return g.Oa(a,function(a){return"dropshadow"==a})?new g.mh(0,7,7,0):new g.mh(0,0,0,0)},rAa=function(a,b,c){var d=new q2;
d.moveTo(a.left+b+c,a.top+c);d.Mc(a.left+a.width-b-c,a.top+c);r2(d,b,b,-90);d.Mc(a.left+a.width-c,a.top+a.height-b-c);r2(d,b,b,0);d.Mc(a.left+b+c,a.top+a.height-c);r2(d,b,b,90);d.Mc(a.left+c,a.top+b+c);r2(d,b,b,180);d.close();return d},sAa=function(a,b,c,d){var e=a.D;
e?a=new n2(e.B*b/100,e.D*c/100,e.C*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new m2(a.bgColor,d?Math.max(b,.9):b));return a},f3=function(a,b){var c=g.qh(a);
c.expand(qAa(b));return new g.ph(c.left,c.top,c.right-c.left,c.bottom-c.top)},tAa=function(a,b,c){if(c.length&&(b=g.Id(window.document,"g",void 0,b),b.length)){var d=pAa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=oAa(d),a=0<d.childNodes.length?dza(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},g3=function(){a3.call(this);
this.C=0},uAa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},h3=function(a){a3.apply(this,arguments)},i3=function(a){a3.apply(this,arguments)},j3=function(a){g3.apply(this,arguments)},k3=function(a,b,c,d,e){g.K.call(this);
this.o=a;this.Z=b;this.F=c;this.fa=d;this.ca=e;this.J=!1;this.Y=new g.cG(this);g.M(this,this.Y);this.O=this.D=this.G=this.M=this.A=null;this.ba=!1;this.aa=this.K=this.L=null;this.rq=new g.Bl(this.iL,100,this);g.M(this,this.rq);this.H=new g.V(this.dB,500,this);g.M(this,this.H);this.V=this.B=this.C=null},vAa=function(a,b){var c=(0,g.B)(function(a,c,f){c=f?l3(this,c,(0,g.B)(f,this)):l3(this,c);
this.Y.W(b,a,c)},a);
c("mouseover","G",a.MC);c("mouseout","F",a.Xh);c("click","D");c("touchend","D")},wAa=function(a){if(a.o.D){if(Y2(a.o,function(a){return"close"==a.type}))var b=a.A;
else a.C=g.Vd("DIV","annotation-close-button"),g.N(a.C,!1),g.BF(a.C,"annotation_id",a.o.id),a.A.appendChild(a.C),b=a.C;var c=function(a){a.stopPropagation()};
a.Y.W(b,"click",l3(a,"E",c));a.Y.W(b,"touchend",l3(a,"E",c))}},l3=function(a,b,c){return(0,g.B)(function(a){if(this.ca)c&&c(a);
else if(a.event.target instanceof window.Element){var d=a.event.target;g.N(d,!1);try{var f=window.document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.re(f,"annotation")){var k=window.document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.N(d,
!0)}}d=g.Wh(a.target);a=new g.Ad(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.fa.U(b,this.o)},a)},n3=function(a){if(a.A||a.B){var b=$2(a.o);
if(b){var c=m3(a);if(a.A){b=V2(b,c);var d=g.Q_(g.sU(a.F));g.Uh(a.A,b.width,b.height);g.Ih(a.A,b.left,b.top);a.M=new g.ph(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=$2(a.o))&&d?Eza(d,e.C,e.o?e.o:"xy"):1;var f=iAa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.mh(d,d,d,d));d=new g.mh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+"px";"label"==
a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.Q_(g.sU(a.F));var p=g.BU(a.F);g.rh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=xAa(a,23,b,d,e);if(a.C){var t=43-f.width;0<t&&(b.left+f.left-t>n.left&&(f.left-=t),f.width+=t)}t=f;g.Uh(a.D,f.width,f.height);g.Ih(a.D,f.left,f.top)}a.C&&(t?b=new g.Ad(t.left+t.width-23-18,a.ba?
t.top+2:t.top+t.height-18-2):(t=xAa(a,18,b,d,e),b=new g.Ad(t.left,t.top),g.Uh(a.C,t.width,t.height)),g.Ih(a.C,b));a.O=new g.ph(a.M.left+t.left,a.M.top+t.top,t.width,t.height);a.L=a.Y.W(g.sU(a.F),"mousemove",a.JP,a)}else a.D&&(t=e/f*d.height*4.2/100,t=new g.Cd(t,t),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,t=new g.ph(b.width-t.width-e,b.height-t.height-e,t.width,t.height)):t=new g.ph(b.width-t.width-3*d.height/100,(b.height-t.height)/2,t.width,t.height),g.Uh(a.D,t.width,t.height),
g.Ih(a.D,t.left,t.top)),a.C&&(t=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Ih(a.C,t&&e?new g.Ad(b.width-9,-9):t?new g.Ad(b.width-9,45<b.height?9:b.height-9):e?new g.Ad(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Ad(45<b.width?b.width-9-18:-9,b.height-9):new g.Ad(-9,45<b.height?9:b.height-9)))}a.B&&a.B.B(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;t=g.Q_(g.sU(a.F));c.style.fontSize=360*b.textSize*iAa(a.o,t)/100+"px";t=a.o.style;
c.style.textAlign=b.textAlign?b.textAlign:"title"==t||"highlightText"==t?"center":"left";b.C&&(c.style.fontWeight=b.C);a=a.A;c=a.style.overflow;t=(b=g.Kd("annotation-link-icon",a))?g.Yh(b):!1;e=(d=g.Kd("annotation-close-button",a))?g.Yh(d):!1;t&&g.N(b,!1);e&&g.N(d,!1);m=f="";if(n=g.Kd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=k=Uya(a);p=5;for(var v=
Math.floor(k/2);v;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+v,k)):l=Math.max(l-v,p),v=Math.floor(v/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.N(d,!0);t&&g.N(b,!0)}}}},xAa=function(a,b,c,d,e){var f=0<e;
b=new g.ph(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.T(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.T(a.A,"annotation-extend-up"),a.ba=!0);return b},o3=function(a){return"label"!=a.o.style||a.B.o},m3=function(a){var b=g.Q_(g.sU(a.F));
if("player_relative"==a.o.F){var c=g.sU(a.F).Va();b=new g.ph(-b.left,-b.top,c.width,c.height)}else b=new g.ph(0,0,b.width,b.height);return new Kza(b,a.V?$2(a.V):null)},yAa=function(a,b){return b?new g.ph(a.x+b.left,a.y+b.top,b.width,b.height):null},p3=function(a,b,c){g.K.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.B=this.isVisible=!1;zAa(b,a)},zAa=function(a,b){gAa(a,function(c){return new kAa(a.id,c,b)})},AAa=function(a){a.A.unsubscribe("resize",a.LC,a);
a.A.unsubscribe("onVideoAreaChange",a.EE,a)},q3=function(a){a.o&&(a.o.stop(),a.o=null)},BAa=function(a,b,c){k2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=R2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},r3=function(a,b,c){k2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.C=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=R2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=R2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},CAa=function(a,b,c){r3.call(this,a,b,c);
this.J=b.ypc_flow_type;this.G=b.innertube_request_params},DAa=function(a,b,c){k2.call(this,a,b,c);
this.C=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=R2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},EAa=function(a,b,c){k2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.C=null;if(a=b.signin_url)this.C=R2({target:"current",value:a});this.J=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},GAa=function(a,b,c){r3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new FAa(a[b]))},FAa=function(a){this.merchant=g.H(a.merchant);
this.price=g.H(a.price)},HAa=function(a,b,c){r3.call(this,a,b,c);
this.M=b.ypc_item_type;this.J=b.ypc_item_id;this.G=b.ypc_flow_type},IAa=function(a,b,c){k2.call(this,a,b,c);
this.C=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=R2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},s3=function(a,b,c){k2.call(this,a,b,c);
this.J=b.image_url;this.C=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=R2({target:b.target||"new",value:b.url})},JAa=function(a){this.o=a;
this.A={}},KAa=function(a){var b={};
b=(b["iv-event"]=1,b);g.yU(a.o,"iv",b,void 0)},w3=function(a,b,c,d){if(b){var e=t3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=u3(a,"cta_annotation_shown",e,c);v3(a,e,LAa(b,d))}},x3=function(a,b,c,d,e,f){if(b){var k=t3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.nc(k,d);b=u3(a,"cta_annotation_clicked",k,e);v3(a,k,b,c,f)}},y3=function(a,b){if(b){var c=t3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=u3(a,"cta_annotation_closed",c);v3(a,c,d)}},LAa=function(a,b){return b?(0,g.J)(a,g.Ha(function(a,b){return g.yn(b,a)},b)):a},u3=function(a,b,c,d){d=d?g.bb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Z(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.jz){if((b=a.jz[b])&&g.RH(b)){a=g.tb("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Gq){b=g.JE(a.Gq,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},v3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||((0,window.clearTimeout)(k),l=!0,d())};
k=(0,window.setTimeout)(function(){l=!0;d()},1E3)}(0,g.D)(c||[],function(a){f++;
g.iF(a,m)});
e&&(f++,0!=e&&a.o.fj(e,m));g.yU(a.o,"iv",b,m)},t3=function(a,b){var c={};
if(b){var d=new g.gn(b);(0,g.D)(d.Jb(),function(a){c[a]=(0,window.escape)(d.get(a,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Z(a.o).playerStyle;return c},z3=function(a,b,c,d,e){e=t3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;v3(a,e,d)},A3=function(a,b,c,d){c&&(c=t3(a,c),c["iv-event"]=b,v3(a,c,d))},MAa=function(a,b,c,d,e,f,k){this.A=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.B=k},B3=function(a,b,c){this.o=a;
this.C=b;this.D=c;this.A=new g.Ep(null)},OAa=function(a,b){var c=[];
(0,g.D)(b.choices,function(a){c.push({I:"li",N:b.G+"-"+a.index.toString(),P:[{I:"label",P:[{I:"input",N:"iv-card-poll-choice-input",T:{type:"checkbox",role:"radio",name:b.G+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{I:"span",N:"iv-card-poll-choice-text",P:[{I:"span",N:"iv-card-poll-choice-percent"},C3(this,"span",void 0,a.desc)]}]},{I:"div",N:"iv-card-poll-result",P:[{I:"div",N:"iv-card-poll-result-bar"}]}]})},a);
var d={I:"ul",T:{role:"radiogroup"},P:c},e={};b.C&&(e["aria-label"]=g.jV("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{I:"div",N:"iv-card-content",P:[C3(a,"h2",e,b.title),{I:"form",P:[{I:"fieldset",P:[d]}]}]}];b.C&&(f.push("iv-card-unavailable"),d.push({I:"div",ea:["iv-card-sign-in"],P:[{I:"h2",da:"Want to vote?"},{I:"a",ea:["iv-card-sign-in-button","iv-button"],T:{href:S2(b.C)},P:[{I:"span",ea:["iv-button-content"],da:"Sign in"}]}]}));f=new g.W({I:"div",
ea:f,P:d});d=f.element;NAa(b,d);Pya(a.o.A,d,g.Ha(a.G,b),a);(0,g.D)(g.Jd("iv-card-poll-choice-input",d),function(a){this.o.A.W(a,"focus",g.Ha(this.B,!0));this.o.A.W(a,"blur",g.Ha(this.B,!1))},a);
b.C&&(d=g.Kd("iv-card-sign-in-button",d),a.C(d,b.C,b.id,b.Od,b.B,b.A.click,5));return f},F3=function(a,b,c,d){var e=b.displayDomain?{I:"div",
N:"iv-card-image-text",da:b.displayDomain}:"",f=PAa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{I:"a",N:"iv-click-target",T:{href:S2(b.url)},P:[D3(b.imageUrl,e),{I:"div",N:"iv-card-content",P:[C3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({I:"div",ea:["iv-card-sign-in"],P:[C3(a,"h2",void 0,b.L||""),{I:"p",da:b.K},{I:"a",ea:["iv-card-sign-in-button","iv-button"],T:{href:S2(b.o)},P:[C3(a,"span","iv-button-content","Sign in")]}]});k=new g.W({I:"div",ea:k,P:e});E3(a,k,b,c,d);return k},QAa=
function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.C?{I:"span",ea:d,T:e,da:b.C}:"";c={I:"div",ea:["iv-card",c],P:[{I:"a",N:"iv-click-target",T:{href:S2(b.url)},P:[D3(b.J,d?{I:"div",N:"iv-card-image-text",P:[d,b.priceText]}:""),{I:"div",N:"iv-card-content",P:[{I:"h2",N:"iv-card-primary-link",da:b.title},G3(a,b)]}]}]};c=new g.W(c);E3(a,c,b);return c},H3=function(a,b){return b.customMessage?C3(a,"div",
"iv-card-message",b.customMessage):""},D3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",N:"iv-card-image",T:{style:c},P:d}},G3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.D)(b.metaInfo,function(a){c.push(C3(this,"li","",a))},a);
return{I:"ul",N:"iv-card-meta-info",P:c}},C3=function(a,b,c,d){c?g.w(c)?c={"class":c}:g.Ba(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Fp(a.A,d);return{I:b,T:c,da:d}},PAa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.C&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.C+");");d.dir=g.Fp(a.A,b.customMessage);var e=[{I:"span",da:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({I:"span",N:"iv-card-link-icon"}));return{I:"div",ea:c,T:d,P:e}},NAa=function(a,b){var c=0;
(0,g.D)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Kd(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.U(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.Kd("iv-card-poll-choice-percent",f);g.ke(l,g.jV("$PERCENT%",{PERCENT:k}));f=g.Kd("iv-card-poll-result-bar",f);g.Bh(f,"transform","scaleX("+e.toFixed(2)+")")}g.U(b,"iv-card-poll-voted",null!=a.o);g.U(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},RAa=function(a,b,c,d){d?(c&&a.o.videoData.Fa||a.o.o.rd(),a.o.o.isFullscreen()&&a.o.o.ce(),x3(a.o.logger,b.B,d,void 0,b.A.click,5),(a=g.zH())&&g.kH(a,b.F)):b.url&&a.D(b.url,b.id,b.Od,b.B,b.A.click||[],5)},E3=function(a,b,c,d,e){c.o&&SAa(a,g.Jd("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&SAa(a,g.Jd("iv-click-target",b.element),c,c.url,d)},SAa=function(a,b,c,d,e){(0,g.D)(b,function(a){if(e){var b=(0,g.B)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.o.A.W(a,"click",b)}else d&&this.C(a,d,c.id,c.Od,c.B,c.A.click,5)},a)},TAa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},I3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=UAa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},UAa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},VAa=function(a){a=S2(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!I3(a))||(b=g.Ug(g.Tg(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.HE(a);if(!b||!b.v)return null;if(b=b.t)return TAa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.FE(a[1]))&&a.t?TAa(a.t):-1},WAa=function(a){a=S2(a);
a=a.replace(/https?:\/\//g,"");return I3(a)?(a=g.HE(a))&&a.v?a.v:null:null},XAa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},J3=function(a,b){return b?b:I3(a)?"current":"new"},K3=function(a,b){g.K.call(this);
this.Da=a;this.context=b;this.Ex=!1;this.fa=0},L3=function(a,b,c,d,e,f){b=new g.IQ(b,c,{id:d});
g.M(a,b);b.namespace="annotations_module";e&&Qya(b).subscribe("onEnter",e,a);f&&Qya(b).subscribe("onExit",f,a);g.EU(a.context.o,[b])},YAa=function(a){return(0,g.I)()-a.fa},ZAa=function(a,b,c,d,e,f){var k=S2(b);
if(k){var l=J3(k,b.target),m=(0,g.B)(function(){b.o&&this.context.o.rd();var a=this.context.videoData.isDni||!1,d=g.HE(k||"");a&&d&&(d.v||d.list)?g.D0(this.context.o.app,d.v,c,d.list,!1,void 0,void 0):g.gV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=YAa(a);x3(a.context.logger,d,m,n,e,f);I3(k)||(a=g.zH(),d=c.itct,a&&d&&g.kH(a,g.fH(d)))}},O3=function(a,b,c){K3.call(this,b,c);
var d=this;this.A=a;this.Z=null;this.ba=this.Aa=this.D=this.xa=!1;this.aa=null;this.O=new g.V(g.A,c.D.useTabletControls?4E3:3E3);g.M(this,this.O);this.na=new g.V(g.A);g.M(this,this.na);this.F=new B3(c,(0,g.B)(this.Yk,this),(0,g.B)(this.Op,this));this.J=new g.W({I:"div",N:"iv-drawer",T:{id:"iv-drawer"},P:[{I:"div",N:"iv-drawer-header",T:{"aria-role":"heading"},P:[{I:"span",N:"iv-drawer-header-text"},{I:"button",ea:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},
{I:"div",N:"iv-drawer-content"}]});g.M(this,this.J);this.G=this.J.element;this.ia=new g.rV(this.J,330);g.M(this,this.ia);this.Ba=g.Kd("iv-drawer-header-text",this.G);this.C=g.Kd("iv-drawer-content",this.G);this.B=[];this.ua=this.V=this.H=this.ca=this.o=null;this.L=[];L3(this,0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&M3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.D)&&N3(d)});
this.M=this.K=this.ha=null},eBa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&$Aa[c]){c=new $Aa[c](b.id,b.data,b.o);if(!a.xa){g.Tq(a.ma(),["html5-stop-propagation","iv-drawer-manager"]);g.KU(a.A,a.G,5);aBa(a);a.V=g.Kd("ytp-cards-button",a.A.getRootNode());var d=g.Kd("iv-drawer-close-button",a.G);a.ua=d;a.xa=!0}bBa(a,c.id);var e=cBa(a,c);if(e){d={oc:c,Cs:e.element,PB:!1};var f=dBa(a,d);g.eb(a.B,f,0,d);e.ya(a.C,f);a.Do();c.autoOpen?L3(a,c.startMs,0x8000000000000,c.id,g.Ha(a.DW,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.EF(d),L3(a,c.startMs,c.startMs+
1,c.id,g.Ha(a.EF,d)),P3(a))}}},fBa=function(a,b){b.data.autoOpenMs&&L3(a,b.data.autoOpenMs,0x8000000000000,"",function(){M3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&L3(a,b.data.autoCloseMs,0x8000000000000,"",function(){N3(a)});
var c=b.data.headerText;g.ke(a.Ba,c);a.V&&a.V.setAttribute("title",c);b.data.eventId&&(a.Z=b.data.eventId);a.ha=g.fH(b.data.trackingParams);a.M=g.fH(b.data.closeTrackingParams);a.K=g.fH(b.data.iconTrackingParams)},bBa=function(a,b){var c=gBa(a,b);
c&&(c==a.o&&(a.o=null),a.A.zC(c.oc.id),g.ce(c.Cs),g.Ya(a.B,c),a.Do(),P3(a))},M3=function(a,b,c,d){if(!a.D){a.ia.show();
a.ca=new g.V(function(){g.T(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.ca.start();a.aa=g.SF(a.C,"mousewheel",(0,g.B)(a.cO,a));a.D=!0;a.fa=(0,g.I)();z3(a.context.logger,a.Z,7,void 0,d&&d.oc?d.oc.B:void 0);var e=g.zH();e&&a.ha&&a.M&&i2(e,[a.ha,a.M]);var f={TRIGGER_TYPE:b};(0,g.D)(a.B,function(b){b.PB||(b.PB=!0,w3(a.context.logger,b.oc.B,b.oc.A.CM,f));e&&i2(e,[b.oc.F])});
a2(a.A);c&&(a.H=new g.V(function(){a.ka=a.V;a.ua.focus()},330),a.H.start())}},N3=function(a){a.D&&(a.ia.hide(),g.TF(a.aa),a.aa=null,g.Uq(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,a2(a.A),a.H&&a.H.stop(),a.H=new g.V(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},aBa=function(a){var b=g.Kd("iv-drawer-close-button",a.G);
a.context.A.W(b,"click",a.aK,a);a.context.A.W(a.C,"touchend",function(){a.O.start()});
a.context.A.W(a.C,"scroll",a.mK,a);a.context.B.subscribe("onHideControls",function(){a.ba=!0});
a.context.B.subscribe("onShowControls",function(){a.ba=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.ba=g.Sq(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.vG("iv-button-shown",a.XM,a));a.L.push(g.vG("iv-button-hidden",a.WM,a));a.L.push(g.vG("iv-teaser-shown",a.aN,a));a.L.push(g.vG("iv-teaser-hidden",a.ZM,a));a.L.push(g.vG("iv-teaser-clicked",a.YM,a))},cBa=function(a,b){switch(b.type){case "simple":return F3(a.F,b);
case "collaborator":var c=a.F,d={I:"div",ea:["iv-card","iv-card-channel"],P:[{I:"a",ea:["iv-click-target"],T:{href:S2(b.url),"data-ytid":b.channelId},P:[D3(b.profileImageUrl),{I:"div",N:"iv-card-content",P:[H3(c,b),{I:"h2",N:"iv-card-primary-link",da:b.title},G3(c,b)]}]}]};d=new g.W(d);E3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.B)(c.F,c,b),F3(c,b,d,d);case "episode":return QAa(a.F,b,"iv-card-episode");case "movie":return QAa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={I:"div",
ea:["iv-card","iv-card-playlist"],P:[{I:"a",N:"iv-click-target",T:{href:S2(b.url)},P:[D3(b.C,{I:"div",N:"iv-card-image-overlay",P:[{I:"span",N:"iv-card-playlist-video-count",da:b.playlistVideoCount.toString()}]}),{I:"div",N:"iv-card-content",P:[H3(c,b),C3(c,"h2","iv-card-primary-link",b.title),G3(c,b)]}]}]},d=new g.W(d),E3(c,d,b),d;case "poll":return OAa(a.F,b);case "productListing":c=a.F;var e=!g.Ua(b.offers);d=["iv-card"];var f="",k=PAa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",
e=b.offers[0],k=[],e.price&&k.push({I:"div",N:"iv-card-offer-price",da:e.price}),e.merchant&&k.push({I:"div",N:"iv-card-offer-merchant",da:e.merchant}),k={I:"div",P:k});d={I:"div",ea:d,T:{tabindex:"0"},P:[{I:"a",ea:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+b.imageUrl+");",href:S2(b.url),"aria-hidden":"true",tabindex:"-1"}},{I:"div",N:"iv-card-content",P:[b.sponsored?{I:"div",N:"iv-card-sponsored",P:["Sponsored",{I:"div",N:"iv-ad-info-container",P:[{I:"div",N:"iv-ad-info",
da:"{{adInfo}}"},{I:"div",N:"iv-ad-info-icon-container",P:[{I:"div",N:"iv-ad-info-icon"},{I:"div",N:"iv-ad-info-callout"}]}]}]}:"",{I:"a",N:"iv-click-target",T:{href:S2(b.url)},P:[C3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.Xd("span");g.ke(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.Fb(f,"adInfo");E3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.B)(c.H,c,b),F3(c,b,d,d);case "video":return c=a.F,d=b.isLiveNow?{I:"span",
ea:["yt-badge","yt-badge-live"],da:"LIVE NOW"}:"",d={I:"div",ea:["iv-card","iv-card-video"],P:[{I:"a",N:"iv-click-target",T:{href:S2(b.url)},P:[D3(b.C,b.videoDuration?{I:"span",N:"iv-card-video-duration",da:b.videoDuration}:""),{I:"div",N:"iv-card-content",P:[H3(c,b),C3(c,"h2","iv-card-primary-link",b.title),G3(c,b),d]}]}]},d=new g.W(d),E3(c,d,b),d}return null},dBa=function(a,b){if(0==a.B.length)return 0;
var c=g.Pa(a.B,function(a){return b.oc.startMs>a.oc.startMs||b.oc.startMs==a.oc.startMs&&b.oc.timestamp>=a.oc.timestamp?!0:!1});
return-1==c?0:c+1},hBa=function(a){return a.o?"productListing"==a.o.oc.type:(0,g.Im)(a.B,function(a){return"productListing"==a.oc.type})},P3=function(a){g.U(a.A.getRootNode(),"ytp-cards-shopping-active",hBa(a))},iBa=function(a,b){if(a.J.A){var c=new f2([0,
a.C.scrollTop],[0,b.Cs.offsetTop],600,bza);a.context.C.W(c,"animate",function(b){a.C.scrollTop=b.y});
a.context.C.W(c,"finish",function(b){a.C.scrollTop=b.y});
c.play()}else g.bI(a.J,!0),a.C.scrollTop=b.Cs.offsetTop,g.bI(a.J,!1)},Q3=function(a){return a.o&&a.o.oc?a.o.oc:a.B[0]&&a.B[0].oc?a.B[0].oc:null},gBa=function(a,b){return g.Oa(a.B,function(a){return a.oc.id==b})},R3=function(a,b,c){K3.call(this,a,b);
this.annotation=c;this.isActive=!1},jBa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&L3(a,a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},S3=function(a,b,c){R3.call(this,a,b,c);
this.A=null;this.G=!1;this.B=null;this.C=!1;this.H=0;this.o=this.F=this.D=null},T3=function(a,b,c){R3.call(this,a,b,c);
this.J=this.D=this.K=!1;this.G=5E3;this.C=null;this.H=g.Vd("DIV","iv-promo-contents");this.A=this.B=this.o=null;this.F=new g.V(function(){this.o.setAttribute("aria-hidden",!0);g.N(this.B,!1);g.N(this.A,!0)},700,this);
g.M(this,this.F)},kBa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.ma().setAttribute("aria-hidden",!0);a.ma().setAttribute("aria-label","Promotion");a.ma().tabIndex=0;var e=a.annotation.Ya(),f=b.image_url;if(f){var k=g.Vd("DIV",["iv-promo-img","iv-click-target"]);f=g.Vd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Vd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Vd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Yk(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.Vd("A","iv-promo-txt"),g.rd(f,S2(e)),a.o=f):a.o=g.Vd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Vd("P",null,g.Vd("STRONG",null,b.text_line_1));var m=g.Vd("P",null,g.Vd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
a.context.D.experiments.o("web_center_align_action_cta")&&d.push("iv-promo-website-card-cta-center-aligned");var n=g.Vd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Vd("BUTTON",["iv-button","iv-promo-button"],g.Vd("SPAN","iv-button-content",f));var p=g.Vd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Yk(a.ma(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.T(a.o,"iv-click-target");e&&a.Yk(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=
g.Vd("P",null,g.Vd("SPAN",null,b.text_line_1)),m=g.Vd("P",null,g.Vd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Vd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.T(a.o,"iv-click-target"),e&&a.Yk(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.Vd("DIV","iv-promo-actions");a.A=g.Vd("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="Expand";a.context.A.W(a.A,
"click",g.Ha(a.Mt,5E3),a);c.appendChild(a.A);g.N(a.A,!1);a.context.A.W(a.ma(),"mouseover",a.kL,a);a.context.A.W(a.ma(),"mouseout",a.jL,a);a.context.A.W(a.ma(),"touchend",g.Ha(a.Mt,5E3),a);a.B=g.Vd("BUTTON",["iv-promo-close","ytp-button"]);a.B.title="Close";a.context.A.W(a.B,"click","cta"==a.annotation.style&&b.text_line_3?a.YK:a.KP,a);c.appendChild(a.B);g.Tq(a.ma(),d);k&&(a.ma().appendChild(k),n&&k.appendChild(n));a.ma().appendChild(a.H);a.ma().appendChild(c)},lBa=function(a){a.D||a.J||a.C||(g.T(a.ma(),
"iv-promo-collapsed"),a.D=!0,a.F.start())},mBa=function(a){a.F.stop();
a.D&&(g.Vq(a.ma(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.N(a.A,!1),g.N(a.B,!0))},nBa=function(a,b){a.C||(a.C=g.Ig(function(){U3(this);
lBa(this)},b,a))},U3=function(a){a.C&&(g.Jg(a.C),a.C=null)},V3=function(a){g.UU.call(this,a);
this.K=!1;this.J=0;this.A={};this.L={};this.kb=new JAa(a);this.G=new g.fG(this);g.M(this,this.G);this.F=this.B=null;this.G.R(this.player,"onVideoAreaChange",(0,g.B)(this.U,this,"onVideoAreaChange"));this.G.R(this.player,"onHideControls",(0,g.B)(this.U,this,"onHideControls"));this.G.R(this.player,"onShowControls",(0,g.B)(this.U,this,"onShowControls"));this.G.R(this.player,"resize",(0,g.B)(this.U,this,"resize"));this.G.R(this.player,"presentingplayerstatechange",(0,g.B)(this.U,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.MS,this);this.subscribe("onShowControls",this.VU,this);this.subscribe("presentingplayerstatechange",this.cU,this);this.subscribe("resize",this.hw,this);this.subscribe("G",this.zN,this);this.subscribe("F",this.Xh,this);this.subscribe("D",this.vR,this);this.subscribe("E",this.aS,this);g.Z(this.player).G.subscribe("vast_info_card_add",this.DE,this);this.V=new g.fG(this);g.M(this,this.V);this.V.R(this.player,g.KQ("annotations_module"),this.xN);this.V.R(this.player,
"crx_annotations_module",this.yN);this.O=g.Vd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.Vd("DIV","video-custom-annotations");this.D=new g.W({I:"div",ea:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.D);g.KU(this.player,this.D.element,4);this.D.hide();this.C=new g.W({I:"div",ea:["ytp-iv-video-content"]});g.M(this,this.C);g.Zd(this.C.element,g.Vd("DIV","video-annotations",this.O,this.Z));this.H=this.o=null;this.M=[];oBa(this)&&this.load();var b=g.Xd("STYLE");
(window.document.getElementsByTagName("HEAD")[0]||window.document.body).appendChild(b);g.sf(this,function(){g.ce(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},pBa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},oBa=function(a){var b=g.Z(a.player);
a=a.player.getVideoData();return 1==(b.kh||a.kh)&&!a.pl||null!==b.G.get(a.videoId)},qBa=function(a,b,c){a.K=!0;
a.F=g.RE(b,c)},rBa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(rBa(a,e))}return c},sBa=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},uBa=function(a,b){var c=tBa(a,b);
if(!c&&"marker"!=b.type)return null;fAa(b,function(a){a=(0,g.B)(this.pV,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new p3(a.ia,b,c);g.M(d,c);return d},vBa=function(a,b){var c=g.Vd("DIV",["annotation",
"annotation-type-custom"]);g.N(c,!1);var d=null;switch(b.type){case "branding":if(g.Z(a.player).Gc)break;a.D.element.appendChild(c);d=new S3(c,W3(a),b);break;case "promotion":g.KU(a.player,c,4),d=new T3(c,W3(a),b)}d&&d.Zq();return d},yBa=function(a){var b=a.player.getVideoData();
if(b.Sf){var c=g.Z(a.player),d=c.G.get(b.videoId);if(d){var e={format:"XML",hd:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.hd.gaming="1");e.Ld=(0,g.B)(function(a,b,c){sBa(this,a,b)||(a=g.zE(c)&&c.responseXML?c.responseXML:null)&&X3(this,a)},a,a.J,b.videoId);
g.QG()&&(e.Ld=wBa(a,e.Ld));e.Tb={ic_only:"1"};xBa(e,d);a.K=!0;g.RE(b.Sf,e)}}},xBa=function(a,b){a.method="POST";
a.Tb=a.Tb||{};b.Bs&&(a.Tb.ic_coll=b.Bs);b.yi&&(a.Tb.ic_xml=b.yi);b.bl&&(a.Tb.ic_track=b.bl)},zBa=function(a){var b=new g.W({I:"div"});
g.N(b.element,!1);var c=new O3(a.player,b.element,W3(a));g.M(c,b);b.ya(a.D.element);c.Zq();return c},W3=function(a){if(!a.H){var b=new g.cG(a);
g.M(a,b);var c=new g.qn(a);g.M(a,c);a.H=new MAa(b,c,g.Z(a.player),a.player.getVideoData(),a.kb,a.player,a.ia)}return a.H},X3=function(a,b){var c=!1;
ABa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=rBa(a,d[e]),k=null;try{k=cAa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=vBa(a,k))g.M(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=zBa(a),g.M(a,a.o)),"card"==k.type?eBa(a.o,k):fBa(a.o,k),c=!0;else if(f=uBa(a,k))g.M(a,f),a.A[k.id]=f}}c&&(a2(a.player),a.hw());g.Ob(a.A,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.A&&
(b=this.A[b.segment.A])&&(a.V=b.annotation)}},a)},ABa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.zH();
if(b){var c=g.yH();c&&g.iH(b,c,[g.fH(a)])}}},CBa=function(a,b,c,d){d?BBa(a,b,c):Y3(a,b,c)},Y3=function(a,b,c){if(b=a.A[b])q3(b),c&&c.A?(a=(0,g.B)(a.cB,a,b),b.o=new g.V(a,2E3),b.o.start()):a.cB(b)},BBa=function(a,b,c){if(b=a.A[b])q3(b),c&&c.C?(a=(0,g.B)(a.TF,a,b),b.o=new g.V(a,2E3),b.o.start()):a.TF(b)},DBa=function(a,b){var c=a.player.getVideoData();
if(!c.xo)return!1;var d=S2(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!I3(d))return!1;d=g.HE(d);return d.list||d.p?!1:(d=WAa(b))?c.videoId==d?!0:"new"!=b.target&&g.Z(a.player).o?!0:!1:!1},tBa=function(a,b){if(EBa(b)){var c=b.D||Y2(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new k3(b,(0,g.B)(a.O.appendChild,a.O),a.player,a.ia,c)}return null},EBa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in X2)if(a.style==X2[b])return!0;return!1},Z3=function(a,b,c,d){a.U(jAa(b,d),c,d)},wBa=function(a,b){return(0,g.B)(function(){if(!this.la()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Ha.apply(window,a);this.M.push(g.OG(b))}},a)},Rya=/[^\d]+$/,Sya={cm:1,
"in":1,mm:1,pc:1,pt:1},Tya={em:1,ex:1};b2.prototype.clone=function(){return new b2(this.start,this.end)};
b2.prototype.getLength=function(){return this.end-this.start};
var c2={},d2=null;g.C(Zya,g.vf);g.C(f2,g.du);g.h=f2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.tb())return!1;e2(this);this.startTime=a=(0,g.I)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.uq();this.Ue("play");-1==this.o&&this.Ue("resume");this.o=1;var b=g.Ga(this);b in c2||(c2[b]=this);Xya();Yya(this,a);return!0};
g.h.stop=function(a){e2(this);this.o=0;a&&(this.progress=1);$ya(this,this.progress);this.Ue("stop");this.pn()};
g.h.pause=function(){this.tb()&&(e2(this),this.o=-1,this.Ue("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.Ue("destroy");f2.ga.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Wv=function(){this.Ue("animate")};
g.h.Ue=function(a){this.dispatchEvent(new Zya(a,this))};
g.C(g2,f2);g2.prototype.B=g.A;g2.prototype.Wv=function(){this.B();g2.ga.Wv.call(this)};
g2.prototype.pn=function(){this.B();g2.ga.pn.call(this)};
g2.prototype.uq=function(){this.B();g2.ga.uq.call(this)};
g.C(h2,g2);h2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.C(l2,g.Wf);g.h=l2.prototype;g.h.Ht=null;g.h.im=null;g.h.ma=function(){return this.im};
g.h.addEventListener=function(a,b,c,d){g.If(this.im,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Qf(this.im,a,b,c,d)};
g.h.X=function(){l2.ga.X.call(this);var a=this.im;if(a)if(g.Bf(a))a.Ve&&g.Ff(a.Ve);else if(a=g.Lf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Rf(d[e])&&++b}};g.C(p2,l2);p2.prototype.fill=null;g.C(fza,l2);q2.prototype.Uf=null;q2.prototype.ke=null;q2.prototype.Gn=!0;var gza=[2,2,6,6,0];g.h=q2.prototype;g.h.clear=function(){this.vb.length=0;this.Na.length=0;this.Re.length=0;delete this.Uf;delete this.ke;delete this.Gn;return this};
g.h.moveTo=function(a,b){0==g.Ma(this.vb)?this.Re.length-=2:(this.vb.push(0),this.Na.push(1));this.Re.push(a,b);this.ke=this.Uf=[a,b];return this};
g.h.Mc=function(a){var b=g.Ma(this.vb);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.vb.push(1),this.Na.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Re.push(c,d)}this.Na[this.Na.length-1]+=b/2;this.ke=[c,d]};
g.h.close=function(){var a=g.Ma(this.vb);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.vb.push(4),this.Na.push(1),this.ke=this.Uf);return this};
g.h.clone=function(){var a=new this.constructor;a.vb=this.vb.concat();a.Na=this.Na.concat();a.Re=this.Re.concat();a.Uf=this.Uf&&this.Uf.concat();a.ke=this.ke&&this.ke.concat();a.Gn=this.Gn;return a};
g.h.transform=function(a){if(!this.Gn)throw Error("Non-simple path");a.transform(this.Re,0,this.Re,0,this.Re.length/2);this.Uf&&a.transform(this.Uf,0,this.Uf,0,1);this.ke&&this.Uf!=this.ke&&a.transform(this.ke,0,this.ke,0,1);return this};
g.h.isEmpty=function(){return 0==this.vb.length};g.C(iza,p2);s2.prototype.Xa=function(){return this.A};g.C(t2,g.Bv);t2.prototype.B=null;t2.prototype.Tj=function(){return this.jf?g.Vh(this.ma()):g.xa(this.width)&&g.xa(this.height)?new g.Cd(this.width,this.height):null};
t2.prototype.resume=function(){};g.C(jza,l2);g.C(n2,eza);g.C(m2,eza);g.C(u2,fza);u2.prototype.clear=function(){g.ae(this.ma())};
u2.prototype.setSize=function(a,b){x2(this.ma(),{width:a,height:b})};
g.C(kza,iza);g.C(v2,jza);v2.prototype.setSize=function(a,b){x2(this.ma(),{width:a,height:b})};var z2;g.C(w2,t2);var mza=0;g.h=w2.prototype;g.h.tp=function(){var a=o2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=o2(this,"g");this.H=o2(this,"defs");this.B=new u2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.C&&(this.ma().setAttribute("preserveAspectRatio","none"),this.O?this.sr():this.ma().setAttribute("viewBox","0 0 "+(this.C?this.C+" "+this.M:"")))};
g.h.sr=function(){if(this.jf){var a=this.Tj();if(0==a.width)this.ma().style.visibility="hidden";else{this.ma().style.visibility="";var b=a.width/this.C;a=a.height/this.M;this.B.ma().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.Uh(this.ma(),a,b)};
g.h.Tj=function(){if(!g.Dh)return this.jf?g.Vh(this.ma()):w2.ga.Tj.call(this);var a=this.width,b=this.height,c=g.w(a)&&-1!=a.indexOf("%"),d=g.w(b)&&-1!=b.indexOf("%");if(!this.jf&&(c||d))return null;if(c){var e=this.ma().parentNode;var f=g.Vh(e);a=(0,window.parseFloat)(a)*f.width/100}d&&(e=e||this.ma().parentNode,f=f||g.Vh(e),b=(0,window.parseFloat)(b)*f.height/100);return new g.Cd(a,b)};
g.h.clear=function(){this.B.clear();g.ae(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=o2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new v2(a,this);(f||this.B).ma().appendChild(e.ma());return e};
g.h.Mj=function(){var a=this.Tj();w2.ga.Mj.call(this);a||this.dispatchEvent("resize");if(this.O){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.W(nza(),"tick",this.sr);this.sr()}};
g.h.Ll=function(){w2.ga.Ll.call(this);this.O&&this.K.La(nza(),"tick",this.sr)};
g.h.X=function(){delete this.A;delete this.H;delete this.B;this.K.dispose();delete this.K;w2.ga.X.call(this)};g.r(B2,g.UU);g.h=B2.prototype;
g.h.load=function(){g.UU.prototype.load.call(this);if(!C2(g.Z(this.player).playerStyle)){var a=g.Pma(this.player.getVideoData());if(a)a=A2(a,oza(this)),D2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.C&&this.C.abort();a={method:"POST",Ld:(0,g.B)(this.zS,this,a),hd:{v:a},withCredentials:!0};"gaming"==g.Z(this.player).playerStyle&&(a.hd.gaming="1");this.M&&(a.hd.ptype="embedded");var c=this.player.getVideoData().kA;c&&(a.Tb={ad_tracking:c});if(b=g.Oma(b))if(b=g.Xc(b),b=g.Uc(b))this.C=
g.RE(b,a)}}};
g.h.unload=function(){D2(this,null);this.C&&(this.C.abort(),this.C=null);g.UU.prototype.unload.call(this)};
g.h.BN=function(a,b){if(!C2(g.Z(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=A2(b,"new");D2(this,c);return!0}return null};
g.h.CN=function(){return C2(g.Z(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.zS=function(a,b){var c=this.C=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=A2(c,oza(this)))}D2(this,c)};
g.h.mC=function(){if(this.A&&this.A.elements){var a=this.player.CC();if(a&&0!=a.width&&0!=a.height){var b=this.player.Um();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<FBa.length;f++){var k=Math.abs(b.width-FBa[f]);if(-1==e||d>=k)e=f,d=k}d=GBa[e];this.B&&g.Bh(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);
var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Uh(e.element,Math.round(k.width*a.width),f);g.Ih(e.element,m,n);g.Vq(e.element,HBa);m=k.left+k.width/2;k=k.top+l/2;g.T(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Vq(e.element,GBa);g.T(e.element,d);(e=g.Id(window.document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Bh(e,"height",f+"px")}}}}};
g.h.DN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.Sh()?(g.vU(this.player,!0),this.player.hc(window.Infinity),this.K=!0):(G2(this,this.A.impressionUrls),(a=g.zH())&&g.jH(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.T(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.T(b,"ytp-ce-shown");G2(this,c.impressionUrls);(b=g.zH())&&g.jH(b,c.visualElement);
g.Z(this.player).Ob&&this.player.za("endscreenelementshown",a)}};
g.h.EN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.Uq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Uq(b,"ytp-ce-shown");g.Z(this.player).Ob&&this.player.za("endscreenelementhidden",a)}};
g.h.KV=function(a){var b=this;a.target===window&&(new g.V(function(){for(var a in b.o)g.Vq(b.o[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.XD=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Sq(c,"ytp-ce-element");){g.Sq(c,"subscribe-label")&&H2(this,a);if(g.Sq(c,"ytp-ce-channel-subscribe"))return;c=g.he(c)}if(!c||g.Sq(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.ew(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.kr?(H2(this,a),this.vF(),this.player.rd(),c=g.Xc(a.targetUrl),c=g.Uc(c),g.gV(c,void 0,a.Od)):(c=this.player.getVideoData().isDni,
c=(0,g.B)(this.LW,this,c,a.targetUrl,a.Od),c=(0,g.B)(this.vF,this,c),H2(this,a,c))}}};
g.h.LW=function(a,b,c){var d=g.HE(b);a&&d&&(d.v||d.list)?g.D0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.fV(b,c)};
g.h.Tu=function(a,b){g.Sq(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.T(a.element,"ytp-ce-element-hover"):g.Z(this.player).A?(new g.V(function(){g.T(a.element,"ytp-ce-element-hover")},200)).start():g.T(a.element,"ytp-ce-element-hover"),G2(this,b.PL),F2(this,b.id,!0))};
g.h.ew=function(a,b){g.Uq(a.element,"ytp-ce-element-hover");g.Uq(a.element,"ytp-ce-force-expand");F2(this,b.id,!1)};
g.h.vF=function(a){this.player.fj(17,a)};
var FBa=[346,426,470,506,570,640,853,1280,1920],GBa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),HBa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var zza={b_:"current",n2:"new"};var Bza={CLOSE:"close",r2:"openUrl",nJ:"subscribe"},Cza={Nr:"click",CLOSE:"close",u0:"hidden",n3:"rollOut",dJ:"rollOver",gJ:"shown"};var Fza={i5:"xx",j5:"xy",p5:"yx",q5:"yy"};g.r(Lza,U2);var Rza={HH:"anchored",Z2:"rect",z3:"shapeless"};var Wza={CLOSED:"closed",B2:"playerControlShow",dJ:"rollOver",gJ:"shown"};W2.prototype.Ya=function(){var a=eAa(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
W2.prototype.showLinkIcon=function(){return Y2(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var X2={HH:"anchored",KH:"branding",CHANNEL:"channel",a_:"cta",x0:"highlightText",Z0:"label",PLAYLIST:"playlist",M2:"popup",N3:"speech",nJ:"subscribe",n4:"title",VIDEO:"video",c5:"website"},aAa={KH:"branding",wZ:"card",E_:"drawer",w0:"highlight",w1:"marker",S2:"promotion",TEXT:"text",f5:"widget"},bAa={U4:"video_relative",C2:"player_relative"};kAa.prototype.C=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Sb(this.o,function(a){return a});
this.B!=a&&(this.B=a,this.A.U(this.D,a,d))};a3.prototype.ma=function(){return this.D};
a3.prototype.B=function(){};var e3={bevel:1,dropshadow:2};g.r(g3,a3);
g3.prototype.B=function(a,b){var c=$2(a);if(c){var d=V2(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=hAa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.sh(Hza(b,Iza(e,new g.ph(e.H,e.J,e.ol,e.B),b.o))),k=d.clone();c=new g.ph(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=f3(k,c.effects);l=b3(this,k.width,k.height);m=sAa(c,k.width,k.height,
this.o);d=new g.ph(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Ad(f.x-k.left,f.y-k.top);this.C=17*T2(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&Z2(a),t=p?f.borderWidth+1:f.borderWidth;p=(f=t?new s2(t,p?f.A:f.borderColor):null)?f.Xa()/2:0;t=uAa(d,n);var v=this.F(d,e,n,t),z=n.x;n=n.y;var E=d.width,G=d.height,L=d.left;d=d.top;var O=new q2;O.moveTo(L+e+p,d+p);"t"==t&&(O.Mc(v.start,d+p),O.Mc(z,n),O.Mc(v.end,d+p));O.Mc(L+E-e-p,d+p);r2(O,e,e,-90);"r"==t&&(O.Mc(L+E-p,v.start),
O.Mc(z,n),O.Mc(L+E-p,v.end));O.Mc(L+E-p,d+G-e-p);r2(O,e,e,0);"b"==t&&(O.Mc(v.end,d+G-p),O.Mc(z,n),O.Mc(v.start,d+G-p));O.Mc(L+e+p,d+G-p);r2(O,e,e,90);"l"==t&&(O.Mc(L+p,v.end),O.Mc(z,n),O.Mc(L+p,v.start));O.Mc(L+p,d+e+p);r2(O,e,e,180);O.close();y2(l,O,f,m);if(m=this.ma())g.T(m,"annotation-shape"),g.T(m,"annotation-speech-shape"),g.Ih(m,k.left,k.top),g.Uh(m,k.width,k.height),tAa(l,m,c.effects)}}}};
g3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.wd(c-a/2,d+b,d+e-a-b);return new b2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new b2(0,0)};g.r(h3,a3);h3.prototype.B=function(a,b){var c=$2(a);if(c){var d=V2(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=f3(d,e.effects);var f=b3(this,c.width,c.height),k=new g.ph(0,0,d.width,d.height),l=e.cornerRadius;d=new s2(!e.B&&this.o?1:e.B,e.bgColor);var m=new m2("#000",0),n=d?d.Xa()/2+1:0;k=rAa(k,l,n);y2(f,k,d,m);f=this.ma();g.T(f,"annotation-shape");e=e.o;g.Xh(f,this.o?Math.max(e,.9):e);g.Ih(f,c.left,c.top);g.Uh(f,c.width,c.height)}}};g.r(i3,a3);
i3.prototype.B=function(a,b){var c=$2(a);if(c){var d=V2(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=f3(d,c.effects),f=b3(this,e.width,e.height),k=new g.ph(0,0,d.width,d.height);d=sAa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&Z2(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new s2(p,n?m.A:m.borderColor):null)?m.Xa()/2+1:0;k=rAa(k,l,n);y2(f,k,m,d);if(k=this.ma())g.T(k,"annotation-shape"),g.T(k,"annotation-popup-shape"),g.Ih(k,e.left,e.top),g.Uh(k,e.width,e.height),tAa(f,
k,c.effects)}}};g.r(j3,g3);j3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new b2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new b2(0,0)};g.r(k3,g.K);g.h=k3.prototype;g.h.MC=function(){this.J||(this.C&&g.N(this.C,!0),this.D&&g.N(this.D,!0),this.B&&(this.B.o=!0,g.Xh(this.A,o3(this)?1:0),this.B.B(this.o,m3(this))),this.H.isActive()&&this.H.stop(),this.J=!0,this.K=this.Y.Nh(g.sU(this.F),"mouseleave",function(a){this.rq.stop();this.Xh(a)}))};
g.h.Xh=function(){this.J&&(this.O?this.H.start():this.dB(),this.B&&(this.B.o=!1,g.Xh(this.A,o3(this)?1:0),this.B.B(this.o,m3(this))),this.J=!1,this.K&&(this.Y.La(this.K),this.K=null))};
g.h.dB=function(){this.C&&g.N(this.C,!1);this.D&&g.N(this.D,!1)};
g.h.JP=function(a){this.aa=a;this.rq.gm()};
g.h.iL=function(){var a=this.aa,b=new g.Ad(a.clientX,a.clientY),c=g.Mh(this.F.getRootNode()),d=yAa(c,this.M);c=(this.D&&g.Yh(this.D)||this.C&&g.Yh(this.C))&&yAa(c,this.O);d&&d.contains(b)||c&&c.contains(b)?this.MC(a):this.Xh(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.B;var b=!this.A;if(a){var c=m3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new h3:"popup"==this.o.style?d=new i3:"anchored"==this.o.style?d=new g3:"speech"==this.o.style&&(d=new j3);d&&(d.B(this.o,c),this.B=d,c=d.ma())&&(g.N(c,!1),g.T(c,"annotation-type-"+this.o.type.toLowerCase()),this.Z(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.Vd("DIV",c);g.N(this.A,!1);this.o.C&&(this.G=g.Vd("DIV","inner-text"),"label"==this.o.style&&(g.T(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.ke(this.G,this.o.C),this.A.appendChild(this.G));g.BF(this.A,"annotation_id",this.o.id);this.Z(this.A);vAa(this,this.A);if(Z2(this.o)&&this.o.showLinkIcon()){if(d=this.o.Ya())c=this.A,d=new g.$m(S2(d)),c.title=d.A+d.B;this.D=g.Vd("SPAN","annotation-link-icon");g.N(this.D,
!1);this.A.appendChild(this.D)}wAa(this);Z2(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=Tza(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.B&&this.B.ma()&&(this.B.ma().style.zIndex=a)}g.N(this.A,!0);g.Xh(this.A,o3(this)?1:0);n3(this);this.B&&this.B.ma()&&g.N(this.B.ma(),!0)};
g.h.hide=function(){this.A&&g.N(this.A,!1);this.B&&this.B.ma()&&g.N(this.B.ma(),!1);this.L&&(this.Y.La(this.L),this.L=null)};g.r(p3,g.K);g.h=p3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(AAa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.LC,this),this.A.subscribe("onVideoAreaChange",this.EE,this))};
g.h.destroy=function(){if(this.view){AAa(this);var a=this.view;g.dG(a.Y);a.rq.dispose();a.H.dispose();a.A&&g.ce(a.A);a.B&&a.B.ma()&&g.ce(a.B.ma())}q3(this)};
g.h.EE=function(){n3(this.view)};
g.h.LC=function(){n3(this.view)};g.r(BAa,k2);g.r(r3,k2);g.r(CAa,r3);g.r(DAa,k2);g.r(EAa,k2);g.r(GAa,r3);g.r(HAa,r3);g.r(IAa,k2);g.r(s3,k2);B3.prototype.B=function(a,b){var c=g.qe(b.target,"label");c&&g.U(c,"iv-card-poll-choice-focused",a)};
B3.prototype.G=function(a,b){var c=g.re(b.target,"iv-card-poll");if(c)if(a.C)g.Kd("iv-card-sign-in-button",c).click();else{var d=(0,window.parseInt)(Vya(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;NAa(a,c);g.VE(this.o.videoData.Sf,{hd:{action_poll_vote:1},Tb:{poll_id:a.id,index:d,session_token:a.J}});x3(this.o.logger,a.B,void 0,{"link-id":d},
a.A.click,5);(c=g.zH())&&g.kH(c,a.F)}};
B3.prototype.F=function(a){var b=g.y("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.J,a.G)});
RAa(this,a,!0,c)};
B3.prototype.H=function(a){var b=g.y("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Ha(b,a.M,a.J,a.G));RAa(this,a,!1,b)};g.r(K3,g.K);g.h=K3.prototype;g.h.Zq=function(){this.context.B.subscribe("resize",this.Do,this)};
g.h.ma=function(){return this.Da};
g.h.Yk=function(a,b,c,d,e,f,k){this.context.A.W(a,"click",g.Ha(this.Op,b,c,d,e,f||[],k||0),this);this.context.A.W(a,"touchstart",g.Ha(function(){this.Ex=!1}),this);
this.context.A.W(a,"touchmove",g.Ha(function(){this.Ex=!0}),this)};
g.h.Op=function(a,b,c,d,e,f,k){if(this.Ex)return!1;k&&(k.stopPropagation(),k.preventDefault());ZAa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.fa=(0,g.I)()};
g.h.hide=function(){};
g.h.destroy=function(){g.ce(this.ma())};
g.h.Do=function(){};g.r(O3,K3);g.h=O3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.B.length)(a=this.A.getRootNode())?(a=g.Vh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Do=function(){var a=this.isAvailable();g.N(this.ma(),a);g.U(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);a2(this.A)};
g.h.destroy=function(){var a=g.oU(this.A).B;a&&a.Ru(!1,void 0);this.A.getRootNode().removeChild(this.G);g.wG(this.L);g.TF(this.aa);this.ca&&this.ca.dispose();this.H&&this.H.dispose();K3.prototype.destroy.call(this)};
g.h.cO=function(a){this.O.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.C.scrollTop+=a};
g.h.EF=function(a){if(!g.Sq(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.zH(),c=this.o?this.o.oc.D:this.K;b&&c&&j2(b,[c]);this.o=a;P3(this)}g.Yh(this.ma())&&(2==this.context.o.Sa()?b=1==((0,window.isNaN)(void 0)?this.context.o.vC():void 0):(b=(0,window.isNaN)(void 0)?this.context.o.Sh():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.oc.teaserDurationMs&&(b={teaserText:a.oc.teaserText,durationMs:a.oc.teaserDurationMs},(c=g.oU(this.A).B)&&c.Ru(!0,b)));this.na.isActive()||
((!this.D||!this.O.isActive()&&this.ba)&&iBa(this,a),this.na.start(910+a.oc.teaserDurationMs))}};
g.h.DW=function(a){this.D||(this.o=a,P3(this),iBa(this,a),M3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.aK=function(){if(this.D){z3(this.context.logger,this.Z,4,Q3(this).A.close);var a=g.zH();a&&this.M&&g.kH(a,this.M);N3(this)}};
g.h.mK=function(){g.U(this.G,"iv-drawer-scrolled",0<this.C.scrollTop)};
g.h.XM=function(){var a=g.zH(),b=Q3(this);b=b?b.D:this.K;a&&b&&i2(a,[b])};
g.h.WM=function(){var a=g.zH(),b=Q3(this);b=b?b.D:this.K;a&&b&&j2(a,[b])};
g.h.aN=function(){var a=Q3(this);A3(this.context.logger,8,a.B,a.A.UW);var b=g.zH();b&&a&&i2(b,[a.H,a.D])};
g.h.ZM=function(){var a=g.zH(),b=Q3(this);a&&b&&j2(a,[b.H])};
g.h.YM=function(a){var b=Q3(this),c=g.zH();this.o?a?(a=this.context.logger,A3(a,9,b.B,b.A.Ww),a.o.fj(4,void 0),c&&g.kH(c,b.H)):(a=this.context.logger,A3(a,12,b.B,b.A.Ww),a.o.fj(4,void 0),c&&g.kH(c,b.D)):(a=this.context.logger,z3(a,this.Z,12,b.A.Ww),a.o.fj(4,void 0),c&&this.K&&g.kH(c,this.K))};
var $Aa={collaborator:BAa,donation:CAa,episode:s3,movie:s3,playlist:DAa,poll:EAa,productListing:GAa,simple:r3,tip:HAa,video:IAa};g.r(R3,K3);R3.prototype.Zq=function(){K3.prototype.Zq.call(this);jBa(this)};
R3.prototype.show=function(){K3.prototype.show.call(this);var a=g.zH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&i2(a,[g.fH(b.itct)])};
R3.prototype.hide=function(){K3.prototype.hide.call(this);var a=g.zH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&j2(a,[g.fH(b.itct)])};g.r(S3,R3);g.h=S3.prototype;g.h.MW=function(a,b,c,d){this.B.stop();if(!this.C){var e=g.Vh(a);this.o||(g.Th(a,e.width),g.Th(b,e.width));g.Bh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Bh(c,"right","1px");this.C=!0;g.N(a,!0);this.D=new g.V(function(){g.T(this.ma(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.NL=function(a,b){g.Uq(this.ma(),"iv-branding-active");this.F=new g.V((0,g.B)(function(){g.N(a,!1);this.o||g.Th(b,0)},this),250);
this.F.start();this.C=!1};
g.h.show=function(){if(!this.isActive){R3.prototype.show.call(this);if(!this.G){g.T(this.ma(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.Vd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.N(this.A,!1);var b=g.Vd("DIV","branding-img-container",this.A);this.ma().appendChild(b);var c=g.Vd("DIV","iv-branding-context-name");g.ke(c,a.channel_name);var d=g.Vd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.d_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.ya(d);b=g.Vd("DIV","iv-branding-context-subscribe-caret");c=g.Vd("DIV","branding-context-container-inner",b,c,d);g.N(c,!1);d=g.Vd("DIV","branding-context-container-outer",c);g.Bh(d,"right",this.H+"px");this.ma().appendChild(d);var e=this.annotation.Ya();e&&this.Yk(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.B=new g.V(g.Ha(this.NL,c,d),500,this);g.M(this,this.B);this.context.A.W(this.ma(),"mouseover",(0,g.B)(this.MW,this,c,d,b,a.image_height));this.context.A.W(this.ma(),"mouseout",(0,g.B)(this.B.start,this.B,void 0));this.G=!0}w3(this.context.logger,this.annotation.o);g.N(this.ma(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.Wh(a).width;c=g.xa(void 0)?void 0:b;g.Ih(a,c);f=new h2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,aza);g.M(this,f);this.context.C.W(f,
"begin",g.Ha(g.N,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(R3.prototype.hide.call(this),g.N(this.ma(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);R3.prototype.destroy.call(this)};g.r(T3,R3);g.h=T3.prototype;g.h.show=function(){this.isActive||(R3.prototype.show.call(this),this.K||(kBa(this),this.K=!0),g.N(this.ma(),!0),this.annotation&&this.annotation.o&&w3(this.context.logger,this.annotation.o),g.Ig(function(){g.Uq(this.ma(),"iv-promo-inactive")},100,this),this.ma().removeAttribute("aria-hidden"),this.isActive=!0,U3(this),mBa(this),nBa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.T(this.ma(),"iv-promo-inactive"),this.isActive=!1,this.ma().setAttribute("aria-hidden",!0))};
g.h.Op=function(a,b,c,d,e,f,k){return this.D?!1:R3.prototype.Op.call(this,a,b,c,d,e,f,k)};
g.h.Mt=function(a,b){b.stopPropagation();mBa(this);nBa(this,a);this.o.focus()};
g.h.kL=function(a){this.J=!0;this.Mt(500,a)};
g.h.jL=function(){this.J=!1;lBa(this)};
g.h.KP=function(a){a.stopPropagation();this.hide();y3(this.context.logger,this.annotation.o)};
g.h.YK=function(a){a.stopPropagation();U3(this);this.D=!0;g.T(this.ma(),"iv-promo-collapsed-no-delay");this.F.start();y3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();R3.prototype.destroy.call(this)};g.r(V3,g.UU);g.h=V3.prototype;g.h.vN=function(a,b){if(!pBa(g.Z(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Ds(b);c&&X3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(bBa(this.o,b),a2(this.player)),!0}return null};
g.h.wN=function(){return pBa(g.Z(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.hw=function(){if(this.C){var a=g.Q_(g.sU(this.player),!0);g.Uh(this.C.element,a.width,a.height);g.Ih(this.C.element,a.left,a.top)}if(this.o){var b=g.BU(this.player);a=this.o;b=b.width;g.U(a.G,"iv-drawer-small",426>=b);g.U(a.G,"iv-drawer-big",1280<=b)}};
g.h.cU=function(a){this.Vc(a.state);g.X(a.state,2)&&(this.Km()&&this.lC()&&2!=this.player.Sa()&&this.Su(!1),this.Ru(!1))};
g.h.load=function(){g.UU.prototype.load.call(this);this.Vc(g.rU(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.B)(this.DS,this,b,this.J),d=(0,g.B)(function(){this.F=null},this);
g.QG()&&(c=wBa(this,c));c={format:"XML",Ld:c,onError:d,hd:{}};a.isPharma&&(c.hd.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Z(this.player);"gaming"==d.playerStyle&&(c.hd.gaming="1");(b=d.G.get(b))&&xBa(c,b);b=b&&(b.yi||b.Bs);if(!a.wo||b)a.Sf?qBa(this,a.Sf,c):(this.B=(0,g.B)(this.AN,this,c),this.player.addEventListener("videodatachange",this.B));g.KU(this.player,this.C.element,4);this.hw()};
g.h.Vc=function(a){a=!g.iQ(a)&&!g.X(a,1024);g.bI(this.D,a);g.bI(this.C,a)};
g.h.AN=function(a){var b=this.player.getVideoData();b.Sf&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),qBa(this,b.Sf,a))};
g.h.unload=function(){KAa(this.kb);g.IU(this.player,"annotations_module");g.Ob(this.A,function(a){a.destroy()});
g.Ob(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,a2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.UU.prototype.unload.call(this);g.aI(this.C);this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.h.DS=function(a,b,c){this.F=null;if(!sBa(this,b,a)&&(a=g.zE(c)&&c.responseXML?c.responseXML:null)){X3(this,a);g.T(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].B,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.C,f.visible=!0);b=new g.IQ(c,e,f);a.push(b)}}g.EU(this.player,a)}};
g.h.DE=function(a){a==this.player.getVideoData().videoId&&(this.loaded?yBa(this):this.load())};
g.h.xN=function(a){a=a.getId();var b=this.A[a];b&&!b.B&&(b=b.annotation,BBa(this,a),w3(this.kb,b.o))};
g.h.yN=function(a){Y3(this,a.getId())};
g.h.cB=function(a){a&&(a.hide(),Z3(this,"shown",!1,a.annotation.id),this.Vo(a.annotation,"hidden"))};
g.h.TF=function(a){a&&(a.show(),Z3(this,"shown",!0,a.annotation.id),this.Vo(a.annotation,"shown"))};
g.h.pV=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;fAa(d.annotation,function(a){e=e||a.value});
CBa(this,a,b,e)}};
g.h.vR=function(a){if(a&&a.id){var b=a.Ya();if(b){var c=S2(b);if(c){var d=(0,g.B)(this.Vo,this,a,"click");if("new"==J3(c,b.target)||DBa(this,b))d(),d=null;x3(this.kb,a.o,d)}}}};
g.h.Vo=function(a,b){dAa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!DBa(this,c.url))){e=WAa(c.url);var f=VAa(c.url);e?(d.videoId==e?this.player.hc(f||0):(d=W3(this).o,g.D0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&W3(this).o.Nc()&&W3(this).o.hc(f)),d=!0):d=!1;e=!d}e&&(e=g.Z(this.player),(d=S2(c.url))?(f=UAa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Ha(XAa,e.pageId,e.ld),d=new g.$m(d),g.dn(d,e(d.B)),d=d.toString())):d=null,d&&
(this.player.rd(),c=J3(d,c.url.target),e=a.itct,"ei"in g.HE(d)&&(d=g.ih(d,"ei")),g.gV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.MS=function(){Z3(this,"playerControlShow",!1)};
g.h.VU=function(){Z3(this,"playerControlShow",!0)};
g.h.zN=function(a){Z3(this,"rollOver",!0,a.id)};
g.h.Xh=function(a){Z3(this,"rollOver",!1,a.id)};
g.h.aS=function(a){a&&a.id&&(this.A[a.id].B=!0,Y3(this,a.id),y3(this.kb,a.o),this.Vo(a,"close"),Z3(this,"closed",!0,a.id))};
g.h.Km=function(){return!!this.o&&this.o.isAvailable()};
g.h.lC=function(){this.Km();return!!this.o&&this.o.D};
g.h.Su=function(a,b,c){b=void 0===b?!1:b;this.Km();this.o&&(a?c?M3(this.o,c,b):M3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):N3(this.o))};
g.h.Ru=function(a,b){this.player.U(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){g.Z(this.player).G.unsubscribe("vast_info_card_add",this.DE,this);g.Uq(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.RG(a[b]);this.M.length=0;g.UU.prototype.X.call(this)};g.SX.annotations_module=V3;g.SX.creatorendscreen=B2;})(_yt_player);
